rudderlabs/terraform-provider-rudderstack

- README.md
- docs/index.md
- examples/main.tf
- go.sum
> Handle sensitive config. Plus other improvements.

- docs/resources/destination_active_campaign.md
- examples/destination_active_campaign.tf
- examples/destination_s3_datalake.tf
- examples/source_cordova.tf
- examples/source_go.tf
- examples/source_ios.tf
- examples/source_java.tf
- examples/source_node.tf
- examples/source_reactnative.tf
- examples/source_ruby.tf
- examples/source_webhook.tf
- examples/source_webhook_shopify.tf
- rudderstack/integrations/destinations/destination_active_campaign.go
- rudderstack/integrations/destinations/destination_active_campaign_test.go
Notion link: 
https://www.notion.so/Terraform-Add-source-config-for-the-newly-added-sources-in-terraform-examples-d423a51d09a34485b6296fcd0afecb6b
https://www.notion.so/rudderstacks/Terraform-Not-able-to-create-s3-datalake-destination-without-having-Glue-configured-167fab2cdadd418bbfcc7a6d64ae7202
> fix: QA fixes 220607

- .github/workflows/release.yml
Notion link: https://www.notion.so/rudderstacks/Terraform-Setup-releases-through-GitHub-Actions-f59a0fe26b124799b469fc8e7b608279
> ci: GitHub Action workflow for new releases

- Makefile
- docs/guides/import.md
- docs/index.md
- docs/resources/connection.md
- examples/main.tf
- rudderstack/provider.go
- templates/guides/import.md.tmpl
- templates/resources/connection.md.tmpl
Notion link: https://www.notion.so/rudderstacks/Terraform-release-0-4-0-cec611a548064e31a7547801a65a1942
> release: bump up release version to 0.4.0

- .goreleaser.yml
Notion link: https://www.notion.so/rudderstacks/Terraform-release-0-4-0-cec611a548064e31a7547801a65a1942
> ci: skip windows/arm64 from goreleaser

- rudderstack/integrations/destinations/destination_mixpanel.go
- rudderstack/integrations/destinations/destination_mixpanel_test.go
> fix: fix issue for consolidatedPageCalls for mixpanel destination

- docs/resources/destination_mixpanel.md
- examples/destination_mixpanel.tf
- rudderstack/integrations/destinations/destination_mixpanel.go
- rudderstack/integrations/destinations/destination_mixpanel_test.go
> Add eventFilteringOption and useNewMapping fields to mixpanel

- .github/pull_request_template.md
Notion link: https://www.notion.so/rudderstacks/Add-Notion-link-and-description-in-terraform-pr-template-0164383f8bfc45a18de067f9dc4cee24
> feat: add Description and notion link in pr template

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
Notion link: https://www.notion.so/rudderstacks/Terraform-release-0-5-0-b285eb2f60b240a1baea62b53e36b8f7
> chore: update version to 0.5.0

- docs/resources/destination_adobe_analytics.md
- examples/destination_adobe_analytics.tf
- rudderstack/integrations/destinations/destination_adobe_analytics.go
- rudderstack/integrations/destinations/destination_adobe_analytics_test.go
> Fixes related to default set fields
> https://www.notion.so/rudderstacks/Terraform-Not-able-to-edit-the-default-fields-from-terraform-0d256e6ffe7e4b409651cbb390b2eb0e
> update config for by default true toggles

- rudderstack/integrations/destinations/destination_adobe_analytics.go
> Update regex for adobe video events to allow some specific values only
> [Notion Link](https://www.notion.so/rudderstacks/Terraform-Adobe-analytics-Able-to-set-any-value-ideally-only-allowed-values-should-able-to-se-b22905d2698a44efbd15bc2ad6bd5044)
> update regex for video events

- Makefile
- docs/guides/import.md
- docs/index.md
- docs/resources/destination_active_campaign.md
- docs/resources/destination_amplitude.md
- docs/resources/destination_bigquery.md
- docs/resources/destination_customerio.md
- docs/resources/destination_facebook_pixel.md
- docs/resources/destination_gcs.md
- docs/resources/destination_google_ads.md
- docs/resources/destination_google_analytics.md
- docs/resources/destination_google_analytics4.md
- docs/resources/destination_google_tag_manager.md
- docs/resources/destination_mixpanel.md
- docs/resources/destination_redis.md
- docs/resources/destination_redshift.md
- docs/resources/destination_s3.md
- docs/resources/destination_s3_datalake.md
- docs/resources/destination_sentry.md
- docs/resources/destination_slack.md
- docs/resources/destination_snowflake.md
- docs/resources/destination_vwo.md
- docs/resources/destination_webhook.md
- docs/resources/destination_zendesk.md
- examples/main.tf
- rudderstack/integrations/destinations/destination_adobe_analytics.go
- rudderstack/provider.go
- rudderstack/resource_destination.go
> Get changes suggested in doc from schema files.
> Update v0.5.0 to v0.6.0 for release.
> Notion Link
> fix: Adobe Analytics- address doc changes from schema, upgrade version to v0.6.0

- Makefile
- docs/guides/import.md
- docs/index.md
- docs/resources/destination_adobe_analytics.md
- docs/resources/destination_snowflake.md
- examples/main.tf
- rudderstack/provider.go
> Updating version to 0.7.0
> Notion Link
> chore: onetrust version upgrade

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
> Update version to 0.7.1
> Notion Link
> chore: update version to v0.7.1

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
> Update version to 0.7.2
> Notion Link
> chore: update version to v0.7.2

- docs/resources/destination_adobe_analytics.md
- docs/resources/destination_amplitude.md
- docs/resources/destination_customerio.md
- docs/resources/destination_facebook_pixel.md
- docs/resources/destination_google_ads.md
- docs/resources/destination_google_analytics.md
- docs/resources/destination_google_analytics4.md
- docs/resources/destination_google_tag_manager.md
- docs/resources/destination_intercom.md
- docs/resources/destination_mixpanel.md
- docs/resources/destination_sentry.md
- docs/resources/destination_vwo.md
- rudderstack/integrations/destinations/destination_adobe_analytics.go
- rudderstack/integrations/destinations/destination_amplitude.go
- rudderstack/integrations/destinations/destination_customerio.go
- rudderstack/integrations/destinations/destination_facebook_pixel.go
- rudderstack/integrations/destinations/destination_google_ads.go
- rudderstack/integrations/destinations/destination_google_analytics.go
- rudderstack/integrations/destinations/destination_google_analytics4.go
- rudderstack/integrations/destinations/destination_google_sheets.go
- rudderstack/integrations/destinations/destination_google_tag_manager.go
- rudderstack/integrations/destinations/destination_intercom.go
- rudderstack/integrations/destinations/destination_mixpanel.go
- rudderstack/integrations/destinations/destination_sentry.go
- rudderstack/integrations/destinations/destination_statsig.go
- rudderstack/integrations/destinations/destination_vwo.go
> Update some destination setting descriptions
> Notion Link
> Chore: Update some destination setting descriptions

- examples/source_android.tf
- rudderstack/integrations/sources/sources.go
- rudderstack/integrations/sources/sources_test.go
- templates/resources/source_android.md.tmpl
> Resolves INT-1291
Adding support for Android source
> Notion Link
> feat: onboard android source

- examples/source_python.tf
- rudderstack/integrations/sources/sources.go
- rudderstack/integrations/sources/sources_test.go
- templates/resources/source_python.md.tmpl
> Onboard Python Source
Resolves INT-2013
> Notion Link
> feat: onboard python source

- Makefile
- docs/guides/import.md
- docs/index.md
- docs/resources/destination_snowflake.md
- examples/destination_snowflake.tf
- examples/main.tf
- rudderstack/integrations/destinations/destination_snowflake.go
- rudderstack/integrations/destinations/destination_snowflake_test.go
- rudderstack/provider.go
> feat: add snowflake new config support and release v0.8.1

- Makefile
- examples/main.tf
- rudderstack/provider.go
> chore: 0.8.2 release.configs

- .github/workflows/release.yml
fix deprecated release flag to clean
> Notion Link
> chore: fix deprecated release flag to clean

- .goreleaser.yml
> chore: update goreleaser version 2

- docs/resources/destination_customerio.md
- examples/destination_customerio.tf
- rudderstack/integrations/destinations/destination_customerio.go
> chore: fix cio datacentre issue

- rudderstack/provider.go
> chore: update provider version

- rudderstack/provider.go
> chore: update provider version for release

- README.md
- docs/resources/destination_s3_datalake.md
- examples/destination_s3_datalake.tf
- rudderstack/integrations/destinations/destination_s3_datalake.go
- rudderstack/integrations/destinations/destination_s3_datalake_test.go
Resolves INT-3111
> Notion Link
> feat: add role based authentication in s3 datalake

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
> chore: bump version for release 3.0.3

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
> bump version to 3.0.4
> Notion Link
> chore: bump version to 3.0.4

- rudderstack/integrations/sources/sources.go
> chore: fix fb leads incorrect api type name

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
> chore: bump to version 3.0.5

- cmd/generatetf/generator/generator.go
- cmd/generatetf/generator/generator_test.go
> fix: generating terraform script during import properly handles empty lists

- CODEOWNERS
update CODEOWNERS to add integrations platform 
> Notion Link
> chore: update CODEOWNERS to integrations platform

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
> chore: bump version to 3.0.6

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
> chore: bump version to 3.0.7

- Makefile
- docs/guides/import.md
- docs/index.md
- examples/main.tf
- rudderstack/provider.go
> chore: bump version 3.1.0
